# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Mod Properties
mod_version=1.0.0
maven_group=com.simplechestshop
archives_base_name=simplechestshop

# Dependencies
minecraft_version=26.3
loader_version=0.19.5
fabric_version=0.161.0+26.3
loom_version=1.18.2
fabric.loom.disableObfuscation=true
